### ISSUE TITLE
"message":"oops, token error"

### ISSUE THREAD

**Issue by empty-id** [QikaiXu/GLaDOS-checkin#31]
好像不行了，试了好几个其他仓库都是一样，估计glados加了什么防护措施？大佬能否解决一下。

**Comment by xuexiji** [comment]
修改一下`checkin.sh`脚本中的`'{"token": "glados.network"}'`，将其修改为`'{"token": "glados.one"}'`，这样应该就可以了

**Comment by EgoistInory** [comment]
确实接口请求改了

**Comment by QikaiXu** [comment]
OK 感谢各位
